### ISSUE TITLE
Make OTEL exporter headers updatable

### ISSUE THREAD

**Issue by aelmekeev** [honeycombio/honeycomb-opentelemetry-web#160]
**Is your feature request related to a problem? Please describe.**

Our public open telemetry collector is behind auth as any other API with short lived tokens.

A follow up on https://github.com/honeycombio/honeycomb-opentelemetry-web/issues/134 from @robwdux it would be nice to have a way to refresh the auth token.

**Describe the solution you'd like**

At the moment we can `headers` at the sdk initialisation. Probably would be nicer to have it as a separate "auth" interface although not sure if this can be generic enough.

In any case the way of updating this configuration when needed - would be nice.

**Describe alternatives you've considered**

I believe at the moment the only way is to shutdown and restart SDK.

**Additional context**

**Comment by nicole0707** [comment]
Do we have an interceptor pattern in place to dynamically attach headers?

**Comment by arriIsHere** [comment]
The OTel-JS library is currently redoing their Exporters. It seems there is a strong intent to support this once that refactor is completed. https://github.com/open-telemetry/opentelemetry-js/pull/3662#issuecomment-2262808849

Since our library depends on theirs we can't really implement this feature until it's available in OTel. Here is the related issue if you would like to keep an eye on it. https://github.com/open-telemetry/opentelemetry-js/issues/2903

**Comment by arriIsHere** [comment]
The OTel-JS library is currently redoing their Exporters. It seems there is a strong intent to support this once that refactor is completed. https://github.com/open-telemetry/opentelemetry-js/pull/3662#issuecomment-2262808849

Since our library depends on theirs we can't really implement this feature until it's available in OTel. Here is the related issue if you would like to keep an eye on it. https://github.com/open-telemetry/opentelemetry-js/issues/2903
